language: python

python:
  - "2.7"
  - "3.4"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov brain --durations=10

after_success:
  - coveralls
