language: python
sudo: false

python:
  - "3.4"

addons:
  apt:
    sources:
      - python-dev
      - libpq-dev
      - postgresql-contrib

install:
  - pip install -r requirements.txt
  # - pip install -r articles/requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test tests --cov stock --durations=10

after_success:
  - coveralls
